// كل أرقام الموازنة في مكان واحد — أي ضبط اقتصادي يبدأ وينتهي هنا.
// القيم منقولة من النسخة الأولى بعد ثلاث جولات ضبط بمحاكاة اقتصادية.

export const BALANCE = {
  score: {
    base: 3,
    balanceWeight: 4,
    synergyWeight: 0.7,
    scopeWeight: 2,
    balanceTolerance: 120,
    hdBonus: 0.5,
    esportsBonus: 1,
    fullQaBonus: 0.4,
    moraleSwing: 0.5,
    festivalBonus: 1,
    quitPenalty: 0.5,
    quickBugPenalty: 0.2,
    normalBugPenalty: 0.1,
    sequelCap: 1.5,
    sequelFromParent: 0.15,
    sequelFatigue: 0.3,
    reviewerSpread: 1.5,
    finalJitter: 0.8,
    /** سرعة ملاحقة خط التوقعات لأداء الاستوديو (rubber band) */
    expectationCatchUp: 0.3,
  },
  sales: {
    scoreExponent: 2.5,
    unit: 100,
    fanWeight: 0.002,
    stageRevenue: (i: number) => 1.5 + i * 1.0,
    trend: 2,
    recession: 0.6,
    publisher: 1.5,
    piracy: 0.7,
    sequel: 1.5,
    prestigePerLevel: 0.1,
    shareFloor: 0.9,
    shareRange: 0.4,
    crossPlatform: 0.15,
    marketerCampaign: 0.12,
    marketerWordOfMouth: 0.05,
  },
  fans: {
    great: [200, 300] as [number, number],
    good: [50, 100] as [number, number],
    ok: [-10, 30] as [number, number],
    hypePerPoint: 2,
    communityMult: 1.5,
    moddingMult: 1.3,
  },
  dlc: {
    scoreExponent: 2.3,
    unit: 60,
    fanWeight: 0.001,
    costRatio: 0.2,
    fatigue: 0.6,
    stageRevenue: (i: number) => 1 + i * 0.35,
    fansBase: 50,
    fansPerScore: 30,
  },
  research: { perGame: 1, highScoreBonus: 2, highScoreAt: 8 },
  morale: { great: 6, good: 3, flop: -8, crunch: -4, resignChance: 0.15, resignBelow: 30 },
  /** النقاط فوق هذه النسبة من السقف ترفع التكلفة 5% لكل نقطة */
  scope: { softCapRatio: 0.7, overCostPerPoint: 0.05 },
  taste: { shift: 8, hotCount: 3, hotBonus: 1 },
  events: { chance: 0.35 },
  contracts: { chance: 0.4, topicChance: 0.5, topicPayBonus: 1.3, deadline: 2 },
};
