/**
 * Builds the vendored Three.js bundle in vendor/three.module.js.
 *
 * The game imports exactly 19 symbols from three. Shipping the full upstream
 * build means shipping the loaders, animation system, curves, post-processing
 * plumbing, every geometry primitive and both renderer backends alongside them —
 * and since r150 upstream also splits into three.module.js + three.core.js, so a
 * naive vendor copy is two files and ~404 KB gzipped. Tree-shaking the same
 * release down to what is actually referenced gives ~129 KB gzipped: smaller than
 * the r128 build this replaced (~226 KB) despite being 57 revisions newer.
 *
 * This is NOT a build step for running the game — index.html still loads the
 * committed bundle directly with no tooling. It is a maintenance script, run by
 * hand when upgrading Three.js, and its output is committed.
 *
 *   node tools/build-three.mjs              # rebuild at the pinned version
 *   node tools/build-three.mjs 0.186.0      # upgrade, then review the screenshots
 *
 * After any upgrade, ALWAYS diff the rendering:
 *   node tools/shot-stages.mjs /tmp/after after
 * and compare against a run from the previous bundle. Colour management and the
 * light model have both changed semantics inside this version range; the mean-RGB
 * numbers that script prints are what catch it.
 *
 * Requires network access (npm) and is the only script in the repo that does.
 */
import { execFileSync } from 'child_process';
import fs from 'fs';
import os from 'os';
import path from 'path';
import zlib from 'zlib';
import { fileURLToPath } from 'url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const VERSION = process.argv[2] || '0.185.1';
const OUT = path.join(ROOT, 'vendor', 'three.module.js');

// Every symbol index.html imports from three. Keep this list in sync with the
// game: an unused entry only costs bytes, but a missing one is a runtime crash.
const EXPORTS = [
  'Scene', 'Color', 'OrthographicCamera', 'WebGLRenderer',
  'AmbientLight', 'DirectionalLight', 'PointLight', 'PCFSoftShadowMap',
  'Group', 'Mesh', 'BoxGeometry', 'MeshStandardMaterial',
  'BufferGeometry', 'BufferAttribute', 'Points', 'PointsMaterial',
  'SRGBColorSpace', 'ColorManagement', 'ACESFilmicToneMapping', 'REVISION',
  'Box3', // used to derive walkable space from the room's own furniture
];

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'three-build-'));
const run = (cmd, args) => execFileSync(cmd, args, { cwd: tmp, stdio: ['ignore', 'pipe', 'inherit'] }).toString();

console.log(`installing three@${VERSION} …`);
fs.writeFileSync(path.join(tmp, 'package.json'), JSON.stringify({ name: 'three-build', private: true, type: 'module' }));
run('npm', ['install', '--no-save', '--silent', `three@${VERSION}`]);

fs.writeFileSync(path.join(tmp, 'entry.js'),
  `// Generated by tools/build-three.mjs — do not edit.\nexport {\n  ${EXPORTS.join(',\n  ')},\n} from 'three';\n`);

console.log('bundling …');
run('npx', ['--yes', 'esbuild', 'entry.js', '--bundle', '--format=esm', '--minify',
  '--target=es2020', '--legal-comments=none', `--outfile=three.slim.js`]);

const bundle = fs.readFileSync(path.join(tmp, 'three.slim.js'), 'utf8');
// Read the revision from the package rather than the bundle: minification renames
// the REVISION binding, so grepping the output silently yields '?'.
const pkgVersion = JSON.parse(fs.readFileSync(path.join(tmp, 'node_modules', 'three', 'package.json'), 'utf8')).version;
const rev = pkgVersion.split('.')[1];
if (!/^\d+$/.test(rev)) throw new Error(`could not derive a revision from three@${pkgVersion}`);

const banner = `/**
 * Three.js r${rev} (npm three@${VERSION}) — tree-shaken to the ${EXPORTS.length} symbols this game uses.
 * Generated by tools/build-three.mjs. Do not edit by hand; re-run that script.
 * @license MIT — Copyright 2010-present Three.js Authors
 * https://github.com/mrdoob/three.js
 */
`;
fs.writeFileSync(OUT, banner + bundle);

const raw = fs.statSync(OUT).size;
const gz = zlib.gzipSync(fs.readFileSync(OUT)).length;
fs.rmSync(tmp, { recursive: true, force: true });

console.log(`\n✓ wrote vendor/three.module.js`);
console.log(`  revision : r${rev}`);
console.log(`  raw      : ${(raw / 1024).toFixed(0)} KB`);
console.log(`  gzipped  : ${(gz / 1024).toFixed(0)} KB`);
console.log(`\nNext: bump VERSION in sw.js, then compare renders with tools/shot-stages.mjs.`);
